CREATE TABLE korisnici (
	korisnik VARCHAR(20) NOT NULL,
	ime VARCHAR(25),
	prezime VARCHAR(25),
	lozinka VARCHAR(20),
	email VARCHAR(100),
	PRIMARY KEY (korisnik)
);

CREATE TABLE grupe (
	grupa VARCHAR(20) NOT NULL,
	naziv VARCHAR(55),
	PRIMARY KEY (grupa)
);

CREATE TABLE uloge (
	korisnik VARCHAR(20) NOT NULL,
	grupa VARCHAR(20) NOT NULL,
	PRIMARY KEY (korisnik, grupa),
	FOREIGN KEY (korisnik) REFERENCES korisnici (korisnik),
	FOREIGN KEY (grupa) REFERENCES grupe (grupa)
);

CREATE TABLE vozila (
	vozilo int NOT NULL,
	proizvodac VARCHAR(50) NOT NULL,
	model VARCHAR(20) NOT NULL,
	vlasnik VARCHAR(20) NOT NULL,
	PRIMARY KEY (vozilo),
	FOREIGN KEY (vlasnik) REFERENCES korisnici (korisnik)	
);
create table dnevnik_Rada (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vrijeme timestamp,
	korisnickoIme char (20),
	adresaRacunala varchar (99),
	ipAdresaRacunala varchar (50),
	nazivOS varchar (30),
	verzijaVM varchar (20),
	opisRada varchar (512)
); 
create table kazne (
	rb int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id int NOT NULL,
	vrijemePocetak bigint NOT NULL,
	vrijemeKraj bigint NOT NULL,
	brzina double NOT NULL,
	gpsSirina double NOT NULL,
	gpsDuzina double NOT NULL,
	gpsSirinaRadar double NOT NULL,
	gpsDuzinaRadar double NOT NULL
); 

create table voznje (
	rb int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id int NOT NULL,
	broj int NOT NULL,
	vrijeme bigint NOT NULL,
	brzina double NOT NULL,
	snaga double NOT NULL,
	struja double NOT NULL,
	visina double NOT NULL,
	gpsBrzina double NOT NULL,
	tempVozila int NOT NULL,
	postotakBaterija int NOT NULL,
	naponBaterija double NOT NULL,
	kapacitetBaterija int NOT NULL,
	tempBaterija int NOT NULL,
	preostaloKm double NOT NULL,
	ukupnoKm double NOT NULL,
	gpsSirina double NOT NULL,
	gpsDuzina double NOT NULL
); 

create table pracenevoznje (
	rb int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id int NOT NULL,
	broj int NOT NULL,
	vrijeme bigint NOT NULL,
	brzina double NOT NULL,
	snaga double NOT NULL,
	struja double NOT NULL,
	visina double NOT NULL,
	gpsBrzina double NOT NULL,
	tempVozila int NOT NULL,
	postotakBaterija int NOT NULL,
	naponBaterija double NOT NULL,
	kapacitetBaterija int NOT NULL,
	tempBaterija int NOT NULL,
	preostaloKm double NOT NULL,
	ukupnoKm double NOT NULL,
	gpsSirina double NOT NULL,
	gpsDuzina double NOT NULL
); 



GRANT SELECT, UPDATE, INSERT ON TABLE kazne TO aplikacija;
GRANT SELECT, UPDATE, INSERT ON TABLE voznje TO aplikacija;
GRANT SELECT, UPDATE, INSERT ON TABLE pracenevoznje TO aplikacija;
GRANT SELECT, UPDATE, INSERT ON TABLE dnevnik_Rada TO aplikacija;

SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;


ALTER TABLE pracenevoznje ADD FOREIGN KEY (id) REFERENCES vozila (vozilo);
ALTER TABLE kazne ADD FOREIGN KEY (id) REFERENCES vozila (vozilo);

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE korisnici TO aplikacija;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE grupe TO aplikacija;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE uloge TO aplikacija;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE vozila TO aplikacija;
