server:
    port: 7070
javax:
    sql:
        DataSource:
            nwtis:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://20.24.5.4:9092/nwtis_3 
                    user: nwtis_3
                    password: nwtis#3
            h2:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://20.24.5.4:9092/nwtis_3 
                    user: nwtis_3
                    password: nwtis#3
            hsqldb:
                dataSourceClassName: org.hsqldb.jdbc.JDBCDataSource
                dataSource:
                    url: jdbc:hsqldb:hsql://20.24.5.3:9001/nwtis_3 
                    user: nwtis_3
                    password: nwtis#3
app:
    radari:
         adresa: 20.24.5.2
         mreznaVrata: 8000 
    vozila:
         adresa: 20.24.5.2
         mreznaVrata: 8001                   
    kazne:
         adresa: 20.24.5.2
         mreznaVrata: 8020
webservis:
    klijenti:
         nadzor:
              baseuri: http://20.24.5.1:8080/ikustura_vjezba_08_dz_3_klijenti/mvc/
