FROM eclipse-temurin:21-jre

COPY ./ikustura_vjezba_08_dz_3_servisi/target/ikustura_vjezba_08_dz_3_servisi-1.1.0.war /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_1.txt /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_2.txt /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_K.txt /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_R.txt /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_V.txt /rest/
COPY ./ikustura_vjezba_08_dz_3_servisi/NWTiS_REST_S.txt /rest/

WORKDIR /rest

EXPOSE 8080

COPY ./docker-entrypoint.servisi.sh /docker-entrypoint.sh
RUN chmod -R 777 /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["rest"]